name: Environments
on: 
  workflow_dispatch:
    inputs:
      environment-name:
        type: environment    # 入力パラーメタでEnvironmentsを切り替え
        default: test
        required: false
        description: Environment name
jobs:
  print: 
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }} # 利用するEnvironmentsを指定
    env:
      USERNAME: ${{ vars.USERNAME }} # Environment variableを参照
      PASSWORD: ${{ secrets.PASSWORD }} # Environment secretを参照
    steps:
      - run: echo "${USERNAME}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
